# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:

- 'master'

variables:

  buildConfiguration: 'Release'

  leaderboardRepository: 'leaderboard'

  webRepository: 'web'

  tag: '$(Build.BuildId)'

  imagePullSecret: 'secret'




stages:

- stage: 'Build'

  displayName: 'Build and push'

  jobs: 

  - job: 'Build'

    displayName: 'Build job'

    pool:

     vmImage: 'ubuntu-latest'

    steps:

    - task: CmdLine@2
      inputs:
        script: |
          cd Tailspin.SpaceGame.Web
          ls  
          docker build -t .
          docker image ls
          docker login -u sravaninaidu9 -p shannu@123
          docker push web

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          docker build -t $(Build.SourcesDirectory)/Tailspin.SpaceGame.LeaderboardContainer/Dockerfile
          docker image ls
          docker login -u sravaninaidu9 -p shannu@123
          docker push sravaninaidu9/leaderboard:latest

    - task: CmdLine@2

      inputs:
    
        script: 'git clone https://github.com/iam-aravind/mslearn-tailspin-spacegame-web-kubernetes.git'

    - task: oc-cmd@3

      inputs:
    
        connectionType: 'OpenShift Connection Service'
    
        openshiftService: 'openshift-servicecon'
    
        cmd: 'oc login --token=oc login --token=sha256~kFkF2sz5qBFSuAJz7PQ8HvxIj_yA9JpKk88Z2DXYK4w --server=https://api.sandbox-m2.ll9k.p1.openshiftapps.com:6443'
    - task: CmdLine@2
    
      inputs:
    
        script: |
          cd mslearn-tailspin-spacegame-web-kubernetes/manifests
          kubectl apply -f deployment.yml
          ls
