trigger:

- 'master'





stages:

- stage: 'Build'

  displayName: 'Build and push'

  jobs: 

  - job: 'Build'

    displayName: 'Build job'

    pool:

     vmImage: 'ubuntu-latest'

    steps:

    - task: Docker@2
      inputs:
        containerRegistry: 'test-docker'
        repository: 'iamaravi/web'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Dockerfile'
        buildContext: '$(Build.Repository.LocalPath)'
        tags: 'latest'

    - task: Docker@2
      inputs:
        containerRegistry: 'test-docker'
        repository: 'iamaravi/Leaderboard'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.LeaderboardContainer/Dockerfile'
        buildContext: '$(Build.Repository.LocalPath)'
        tags: 'latest'

    - publish: '$(Build.SourcesDirectory)/manifests'

      artifact: manifests

   