trigger:

- 'master'





stages:

- stage: 'Build'

  displayName: 'Build and push'

  jobs: 

  - job: 'Build'

    displayName: 'Build job'

    pool:

     vmImage: 'ubuntu-latest'

    steps:

    - task: Docker@2
      inputs:
        containerRegistry: 'openshift-ACR'
        repository: 'web'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Dockerfile'
        buildContext: '$(Build.Repository.LocalPath)'

    - task: Docker@2
      inputs:
        containerRegistry: 'openshift-ACR'
        repository: 'Leaderboard'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.LeaderboardContainer/Dockerfile'
        buildContext: '$(Build.Repository.LocalPath)'

    - publish: '$(Build.SourcesDirectory)/manifests'

      artifact: manifests

    - task: CmdLine@2

      inputs:
    
        script: 'git clone https://github.com/sravaninaidu/mslearn-tailspin-spacegame-web-kubernetes.git'
    - task: oc-cmd@3

      inputs:
    
        connectionType: 'OpenShift Connection Service'
    
        openshiftService: 'openshift-servicecon'
    
        cmd: 'oc login --token=sha256~KcgZYBJx0fJQeUNWtfQqMclgl0cmzYkuR3KTfR_FrKQ --server=https://api.sandbox-m2.ll9k.p1.openshiftapps.com:6443'
    
    - task: CmdLine@2
    
      inputs:
    
        script: |
          cd mslearn-tailspin-spacegame-web-kubernetes/manifests
          az acr login --name openshiftacr --username openshiftacr --password pD2zwFM1w9J6G67YUBlqMi34FryK+uYpdq9W/gYSZS+ACRBruPTq
          kubectl apply -f deployment.yml
          kubectl apply -f service.yml
          ls

