apiVersion : apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec: 
      imagePullSecrets:
        - name: acr-pull-secret
      containers:
        - name: web
          image: docker.io/iamaravi/web:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: leaderboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leaderboard
  template:
    metadata:
      labels:
        app: leaderboard
    spec:
      imagePullSecrets:
       - name: acr-pull-secret
      containers:
        - name: leaderboard
          image: docker.io/iamaravi/leaderboard:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
